### ISSUE TITLE
Crashing on 1.18.2

### ISSUE THREAD

**Issue by ghost** [raoulvdberge/refinedstorageaddons#100]
### Describe the bug

I realize this was probably fixed for 0.9 but I cannot use the 0.9 version on 1.18.2. because it was built for 1.19+

This is what it shows on launch https://i.imgur.com/LmBvP2o.png

I have removed Refined storage addon, and after I had no crashing. Re added and this crash reoccurs again. Removed again and modpack loads fine.

Please fix this for the 1.18.2 version as a lot of the mods are not updated for 1.19+ yet.

### How can we reproduce this bug or crash?

1. Install Refined Storage Addon
2. That's it

### What Minecraft version is this happening on?

Minecraft 1.18.2

### What Forge version is this happening on?

40.2.0

### What Refined Storage Addons version is this happening on?

0.8.2

### Relevant log output

```shell
---- Minecraft Crash Report ----
// Who set us up the TNT?

Time: 3/4/23, 11:26 PM
Description: Mod loading error has occurred

java.lang.Exception: Mod Loading has failed
	at net.minecraftforge.logging.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:55) ~[forge-1.18.2-40.2.0-universal.jar%23120!/:?] {re:classloading}
	at net.minecraftforge.client.loading.ClientModLoader.completeModLoading(ClientModLoader.java:170) ~[forge-1.18.2-40.2.0-universal.jar%23120!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.lambda$new$1(Minecraft.java:557) ~[client-1.18.2-20220404.173914-srg.jar%23115!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:APP:ding.mixins.json:MinecraftMixin,pl:mixin:APP:oauth.mixins.json:MinecraftMixin,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.Util.m_137521_(Util.java:397) ~[client-1.18.2-20220404.173914-srg.jar%23115!/:?] {re:classloading}
	at net.minecraft.client.Minecraft.lambda$new$2(Minecraft.java:551) ~[client-1.18.2-20220404.173914-srg.jar%23115!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:APP:ding.mixins.json:MinecraftMixin,pl:mixin:APP:oauth.mixins.json:MinecraftMixin,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screens.LoadingOverlay.m_6305_(LoadingOverlay.java:135) ~[client-1.18.2-20220404.173914-srg.jar%23115!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:879) ~[client-1.18.2-20220404.173914-srg.jar%23115!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1046) ~[client-1.18.2-20220404.173914-srg.jar%23115!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:APP:ding.mixins.json:MinecraftMixin,pl:mixin:APP:oauth.mixins.json:MinecraftMixin,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:665) ~[client-1.18.2-20220404.173914-srg.jar%23115!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:APP:ding.mixins.json:MinecraftMixin,pl:mixin:APP:oauth.mixins.json:MinecraftMixin,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:205) ~[client-1.18.2-20220404.173914-srg.jar%23115!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:31) ~[fmlloader-1.18.2-40.2.0.jar%2351!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.1.3.jar%2339!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.1.3.jar%2339!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.1.3.jar%2339!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.1.3.jar%2339!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.1.3.jar%2339!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.1.3.jar%2339!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.1.3.jar%2339!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149) [bootstraplauncher-1.0.0.jar:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:57) [ForgeWrapper-mmc2.jar:mmc2] {}
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88) [NewLaunch.jar:?] {}
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126) [NewLaunch.jar:?] {}
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71) [NewLaunch.jar:?] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at java.util.HashMap.computeIfAbsent(HashMap.java:1221) ~[?:?] {re:mixin}
-- MOD refinedstorageaddons --
Details:
	Mod File: /C:/Users/DerpDerpingtonIsHere/AppData/Roaming/PrismLauncher/instances/1.18.2/.minecraft/mods/refinedstorageaddons-0.8.2.jar
	Failure message: Refined Storage Addons (refinedstorageaddons) encountered an error during the sided_setup event phase
		java.util.ConcurrentModificationException: null
	Mod Version: 0.8.2
	Mod Issue URL: https://github.com/refinedmods/refinedstorageaddons
	Exception message: java.util.ConcurrentModificationException
Stacktrace:
	at java.util.HashMap.computeIfAbsent(HashMap.java:1221) ~[?:?] {re:mixin}
	at net.minecraft.client.renderer.item.ItemProperties.register(ItemProperties.java:60) ~[client-1.18.2-20220404.173914-srg.jar%23115!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at com.refinedmods.refinedstorageaddons.setup.ClientSetup.onClientSetup(ClientSetup.java:23) ~[refinedstorageaddons-0.8.2.jar%23100!/:0.8.2] {re:classloading}
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-5.0.3.jar%2336!/:?] {}
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-5.0.3.jar%2336!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%2336!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%2336!/:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:106) ~[javafmllanguage-1.18.2-40.2.0.jar%23117!/:?] {}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:107) ~[fmlcore-1.18.2-40.2.0.jar%23116!/:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}


-- System Details --
Details:
	Minecraft Version: 1.18.2
	Minecraft Version ID: 1.18.2
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 17.0.6, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
	Memory: 2317309448 bytes (2209 MiB) / 4483710976 bytes (4276 MiB) up to 5368709120 bytes (5120 MiB)
	CPUs: 12
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 5 4600H with Radeon Graphics         
	Identifier: AuthenticAMD Family 23 Model 96 Stepping 1
	Microarchitecture: unknown
	Frequency (GHz): 2.99
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: NVIDIA GeForce GTX 1660 Ti
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x2191
	Graphics card #0 versionInfo: DriverVersion=31.0.15.2849
	Graphics card #1 name: AMD Radeon(TM) Graphics
	Graphics card #1 vendor: Advanced Micro Devices, Inc. (0x1002)
	Graphics card #1 VRAM (MB): 512.00
	Graphics card #1 deviceId: 0x1636
	Graphics card #1 versionInfo: DriverVersion=27.20.11028.5001
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 3.20
	Memory slot #0 type: DDR4
	Virtual memory max (MB): 14753.12
	Virtual memory used (MB): 12593.17
	Swap memory total (MB): 7203.80
	Swap memory used (MB): 1073.15
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms512m -Xmx5120m
	ModLauncher: 9.1.3+9.1.3+main.9b69c82a
	ModLauncher launch target: forgeclient
	ModLauncher naming: srg
	ModLauncher services: 
		 mixin PLUGINSERVICE 
		 eventbus PLUGINSERVICE 
		 slf4jfixer PLUGINSERVICE 
		 object_holder_definalize PLUGINSERVICE 
		 runtime_enum_extender PLUGINSERVICE 
		 capability_token_subclass PLUGINSERVICE 
		 accesstransformer PLUGINSERVICE 
		 runtimedistcleaner PLUGINSERVICE 
		 mixin TRANSFORMATIONSERVICE 
		 fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		lowcodefml@null
		javafml@null
	Mod List: 
		supermartijn642configlib-1.1.6-forge-mc1.18.jar   |SuperMartijn642's Config Libra|supermartijn642configlib      |1.1.6               |ENQUEUE_IM|Manifest: NOSIGNATURE
		rechiseled-1.0.12a-forge-mc1.18.jar               |Rechiseled                    |rechiseled                    |1.0.12a             |ENQUEUE_IM|Manifest: NOSIGNATURE
		kleeslabs-forge-1.18.2-11.1.1.jar                 |KleeSlabs                     |kleeslabs                     |11.1.1              |ENQUEUE_IM|Manifest: NOSIGNATURE
		Clumps-forge-1.18.2-8.0.0+17.jar                  |Clumps                        |clumps                        |8.0.0+17            |ENQUEUE_IM|Manifest: NOSIGNATURE
		XaerosWorldMap_1.28.9_Forge_1.18.2.jar            |Xaero's World Map             |xaeroworldmap                 |1.28.9              |ENQUEUE_IM|Manifest: NOSIGNATURE
		cookingforblockheads-forge-1.18.2-12.2.0.jar      |CookingForBlockheads          |cookingforblockheads          |12.2.0              |ENQUEUE_IM|Manifest: NOSIGNATURE
		SimpleStorageNetwork-1.18.2-1.6.2.jar             |Simple Storage Network        |storagenetwork                |1.18.2-1.6.2        |ENQUEUE_IM|Manifest: 1f:47:ac:b1:61:82:96:b8:47:19:16:d2:61:81:11:60:3a:06:4b:61:31:56:7d:44:31:1e:0c:6f:22:5b:4c:ed
		LibX-1.18.2-3.2.18.jar                            |LibX                          |libx                          |1.18.2-3.2.18       |ENQUEUE_IM|Manifest: NOSIGNATURE
		farmingforblockheads-forge-1.18.2-10.0.2.jar      |Farming for Blockheads        |farmingforblockheads          |10.0.2              |ENQUEUE_IM|Manifest: NOSIGNATURE
		bonsaitrees3-3.1.0.jar                            |Bonsai Trees 3                |bonsaitrees3                  |3.1.0               |ENQUEUE_IM|Manifest: NOSIGNATURE
		mcjtylib-1.18-6.0.20.jar                          |McJtyLib                      |mcjtylib                      |1.18-6.0.20         |ENQUEUE_IM|Manifest: NOSIGNATURE
		rftoolsbase-1.18-3.0.12.jar                       |RFToolsBase                   |rftoolsbase                   |1.18-3.0.12         |ENQUEUE_IM|Manifest: NOSIGNATURE
		xnet-1.18-4.0.9.jar                               |XNet                          |xnet                          |1.18-4.0.9          |ENQUEUE_IM|Manifest: NOSIGNATURE
		balm-3.2.5.jar                                    |Balm                          |balm                          |3.2.5               |ENQUEUE_IM|Manifest: NOSIGNATURE
		carryon-1.18.2-1.17.0.8.jar                       |Carry On                      |carryon                       |1.17.0.8            |ENQUEUE_IM|Manifest: NOSIGNATURE
		JustEnoughResources-1.18.2-0.14.1.171.jar         |Just Enough Resources         |jeresources                   |0.14.1.171          |ENQUEUE_IM|Manifest: NOSIGNATURE
		BetterThanMending-1.7.1.jar                       |BetterThanMending             |betterthanmending             |1.7.1               |ENQUEUE_IM|Manifest: NOSIGNATURE
		forge-1.18.2-40.2.0-universal.jar                 |Forge                         |forge                         |40.2.0              |ENQUEUE_IM|Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		mob_grinding_utils-1.18.2-0.4.47.jar              |Mob Grinding Utils            |mob_grinding_utils            |1.18.2-0.4.47       |ENQUEUE_IM|Manifest: NOSIGNATURE
		RSInfinityBooster-1.18.2-2.1+20.jar               |RSInfinityBooster             |rsinfinitybooster             |1.18.2-2.1+20       |ENQUEUE_IM|Manifest: NOSIGNATURE
		refinedstorage-1.10.5.jar                         |Refined Storage               |refinedstorage                |1.10.5              |ENQUEUE_IM|Manifest: NOSIGNATURE
		jei-1.18.2-forge-10.2.1.1002.jar                  |Just Enough Items             |jei                           |10.2.1.1002         |ENQUEUE_IM|Manifest: NOSIGNATURE
		ProjectE-1.18.2-PE1.0.1.jar                       |ProjectE                      |projecte                      |1.0.1               |ENQUEUE_IM|Manifest: NOSIGNATURE
		ironchest-1.18.2-13.2.11.jar                      |Iron Chests                   |ironchest                     |1.18.2-13.2.11      |ENQUEUE_IM|Manifest: NOSIGNATURE
		client-1.18.2-20220404.173914-srg.jar             |Minecraft                     |minecraft                     |1.18.2              |ENQUEUE_IM|Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		TConstruct-1.18.2-3.6.3.111.jar                   |Tinkers' Construct            |tconstruct                    |3.6.3.111           |ENQUEUE_IM|Manifest: NOSIGNATURE
		theoneprobe-1.18-5.1.2.jar                        |The One Probe                 |theoneprobe                   |1.18-5.1.2          |ENQUEUE_IM|Manifest: NOSIGNATURE
		MouseTweaks-forge-mc1.18-2.21.jar                 |Mouse Tweaks                  |mousetweaks                   |2.21                |ENQUEUE_IM|Manifest: NOSIGNATURE
		ironfurnaces-1.18.2-3.3.3.jar                     |Iron Furnaces                 |ironfurnaces                  |3.3.3               |ENQUEUE_IM|Manifest: NOSIGNATURE
		extendedexchange-1802.2.7.jar                     |ExtendedeXchange              |extendedexchange              |1802.2.7            |ENQUEUE_IM|Manifest: NOSIGNATURE
		supermartijn642corelib-1.1.4-forge-mc1.18.jar     |SuperMartijn642's Core Lib    |supermartijn642corelib        |1.1.4               |ENQUEUE_IM|Manifest: NOSIGNATURE
		SkyblockBuilder-1.18.2-3.3.25.jar                 |Skyblock Builder              |skyblockbuilder               |1.18.2-3.3.25       |ENQUEUE_IM|Manifest: NOSIGNATURE
		Ding-1.18.2-Forge-1.4.0.jar                       |Ding                          |ding                          |1.4.0               |ENQUEUE_IM|Manifest: NOSIGNATURE
		jeiintegration_1.18.2-9.0.0.37.jar                |JEI Integration               |jeiintegration                |9.0.0.37            |ENQUEUE_IM|Manifest: NOSIGNATURE
		pipez-1.18.2-1.1.5.jar                            |Pipez                         |pipez                         |1.18.2-1.1.5        |ENQUEUE_IM|Manifest: NOSIGNATURE
		curios-forge-1.18.2-5.0.9.0.jar                   |Curios API                    |curios                        |1.18.2-5.0.9.0      |ENQUEUE_IM|Manifest: NOSIGNATURE
		Mantle-1.18.2-1.9.43.jar                          |Mantle                        |mantle                        |1.9.43              |ENQUEUE_IM|Manifest: NOSIGNATURE
		Xaeros_Minimap_23.1.0_Forge_1.18.2.jar            |Xaero's Minimap               |xaerominimap                  |23.1.0              |ENQUEUE_IM|Manifest: NOSIGNATURE
		topaddons-1.18.2-2.3.1-beta.jar                   |TOP Addons                    |topaddons                     |1.18.2-2.3.1-beta   |ENQUEUE_IM|Manifest: NOSIGNATURE
		oauth-1.1.14-1.18.2.jar                           |OAuth                         |oauth                         |1.1.14              |ENQUEUE_IM|Manifest: NOSIGNATURE
		AutoRegLib-1.7-53.jar                             |AutoRegLib                    |autoreglib                    |1.7-53              |ENQUEUE_IM|Manifest: NOSIGNATURE
		AkashicTome-1.5-20.jar                            |Akashic Tome                  |akashictome                   |1.5-20              |ENQUEUE_IM|Manifest: NOSIGNATURE
		StorageDrawers-1.18.2-10.2.1.jar                  |Storage Drawers               |storagedrawers                |10.2.1              |ENQUEUE_IM|Manifest: NOSIGNATURE
		time-in-a-bottle-2.1.0-mc1.18.1.jar               |Time In A Bottle              |tiab                          |2.1.0-mc1.18.1      |ENQUEUE_IM|Manifest: NOSIGNATURE
		angelring-1.18.2-2.0.2.jar                        |Angel Ring 2                  |angelring                     |2.0.2               |ENQUEUE_IM|Manifest: NOSIGNATURE
		libnonymous-2.1.0.jar                             |libnonymous                   |libnonymous                   |2.1.0               |ENQUEUE_IM|Manifest: NOSIGNATURE
		elevatorid-1.18.2-1.8.4.jar                       |Elevator Mod                  |elevatorid                    |1.18.2-1.8.4        |ENQUEUE_IM|Manifest: NOSIGNATURE
		ftb-ultimine-forge-1802.3.3-build.70.jar          |FTB Ultimine                  |ftbultimine                   |1802.3.3-build.70   |ENQUEUE_IM|Manifest: NOSIGNATURE
		ExtraStorage-1.18.2-2.2.1.jar                     |Extra Storage                 |extrastorage                  |2.2.1               |ENQUEUE_IM|Manifest: NOSIGNATURE
		constructionwand-1.18.2-2.9.jar                   |Construction Wand             |constructionwand              |1.18.2-2.9          |ENQUEUE_IM|Manifest: NOSIGNATURE
		architectury-4.11.89-forge.jar                    |Architectury                  |architectury                  |4.11.89             |ENQUEUE_IM|Manifest: NOSIGNATURE
		ftb-library-forge-1802.3.11-build.177.jar         |FTB Library                   |ftblibrary                    |1802.3.11-build.177 |ENQUEUE_IM|Manifest: NOSIGNATURE
		item-filters-forge-1802.2.8-build.47.jar          |Item Filters                  |itemfilters                   |1802.2.8-build.47   |ENQUEUE_IM|Manifest: NOSIGNATURE
		ftbbackups2-forge-1.18.2-1.0.18.jar               |FTB Backups 2                 |ftbbackups2                   |1.0.18              |ENQUEUE_IM|Manifest: NOSIGNATURE
		ftb-teams-forge-1802.2.10-build.96.jar            |FTB Teams                     |ftbteams                      |1802.2.10-build.96  |ENQUEUE_IM|Manifest: NOSIGNATURE
		ftb-quests-forge-1802.3.14-build.191.jar          |FTB Quests                    |ftbquests                     |1802.3.14-build.191 |ENQUEUE_IM|Manifest: NOSIGNATURE
		appleskin-forge-mc1.18.2-2.4.1.jar                |AppleSkin                     |appleskin                     |2.4.1+mc1.18.2      |ENQUEUE_IM|Manifest: NOSIGNATURE
		moreoverlays-1.20.10-mc1.18.2.jar                 |More Overlays Updated         |moreoverlays                  |1.20.10-mc1.18.2    |ENQUEUE_IM|Manifest: NOSIGNATURE
		refinedstorageaddons-0.8.2.jar                    |Refined Storage Addons        |refinedstorageaddons          |0.8.2               |ERROR     |Manifest: NOSIGNATURE
		polylib-forge-1801.0.2-build.13.jar               |PolyLib                       |polylib                       |1801.0.2-build.13   |ENQUEUE_IM|Manifest: NOSIGNATURE
		extremesoundmuffler-3.30_forge-1.18.2.jar         |Extreme Sound Muffler         |extremesoundmuffler           |3.31_forge-1.18.2   |ENQUEUE_IM|Manifest: NOSIGNATURE
		CobbleForDays-1.5.1.jar                           |Cobble For Days               |cobblefordays                 |1.5.1               |ENQUEUE_IM|Manifest: NOSIGNATURE
		CodeChickenLib-1.18.2-4.1.3.480-universal.jar     |CodeChicken Lib               |codechickenlib                |4.1.3.480           |ENQUEUE_IM|Manifest: 31:e6:db:63:47:4a:6e:e0:0a:2c:11:d1:76:db:4e:82:ff:56:2d:29:93:d2:e5:02:bd:d3:bd:9d:27:47:a5:71
		EnderStorage-1.18.2-2.9.0.182-universal.jar       |EnderStorage                  |enderstorage                  |2.9.0.182           |ENQUEUE_IM|Manifest: 31:e6:db:63:47:4a:6e:e0:0a:2c:11:d1:76:db:4e:82:ff:56:2d:29:93:d2:e5:02:bd:d3:bd:9d:27:47:a5:71
	Crash Report UUID: c6fd5fbb-a3c6-46f1-aad9-5ff6b51b0df0
	FML: 40.2
	Forge: net.minecraftforge:40.2.0
```

**Comment by raoulvdberge** [comment]
This is a rare crash, just restart. 1.18.2 is no longer supported.
