### ISSUE TITLE
Crash Code

### ISSUE THREAD

**Issue by amazingkidd** [raoulvdberge/refinedstorageaddons#23]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  CTMCorePlugin (CTM-MC1.12-0.2.3.12.jar)
  LoadingPlugin (RandomThings-MC1.12.2-4.0.8.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.63+beta.107.jar)
Contact their authors BEFORE contacting forge

// I just don't know what went wrong :(

Time: 1/26/18 4:19 PM
Description: Initializing game

java.lang.NullPointerException: Initializing game
	at net.minecraftforge.fml.common.versioning.ComparableVersion.parseVersion(ComparableVersion.java:371)
	at net.minecraftforge.fml.common.versioning.ComparableVersion.<init>(ComparableVersion.java:362)
	at net.minecraftforge.fml.common.versioning.DefaultArtifactVersion.<init>(DefaultArtifactVersion.java:31)
	at net.minecraftforge.fml.common.versioning.DefaultArtifactVersion.<init>(DefaultArtifactVersion.java:42)
	at net.minecraftforge.fml.common.FMLModContainer.getProcessedVersion(FMLModContainer.java:628)
	at net.minecraftforge.fml.common.Loader.sortModList(Loader.java:235)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:547)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:227)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:466)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraftforge.fml.common.versioning.ComparableVersion.parseVersion(ComparableVersion.java:371)
	at net.minecraftforge.fml.common.versioning.ComparableVersion.<init>(ComparableVersion.java:362)
	at net.minecraftforge.fml.common.versioning.DefaultArtifactVersion.<init>(DefaultArtifactVersion.java:31)
	at net.minecraftforge.fml.common.versioning.DefaultArtifactVersion.<init>(DefaultArtifactVersion.java:42)
	at net.minecraftforge.fml.common.FMLModContainer.getProcessedVersion(FMLModContainer.java:628)
	at net.minecraftforge.fml.common.Loader.sortModList(Loader.java:235)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:547)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:227)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:466)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 836942512 bytes (798 MB) / 1089470464 bytes (1039 MB) up to 4056416256 bytes (3868 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4352m -Xms256m -XX:PermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.40 Powered by Forge 14.21.1.2443 65 mods loaded, 65 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	U	minecraft{1.12} [Minecraft] (minecraft.jar) 
	U	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	U	FML{8.0.99.99} [Forge Mod Loader] (forge-1.12-14.21.1.2443.jar) 
	U	forge{14.21.1.2443} [Minecraft Forge] (forge-1.12-14.21.1.2443.jar) 
	U	appleskin{1.0.9} [AppleSkin] (AppleSkin-mc1.12-1.0.9.jar) 
	U	autoreglib{1.3-15} [AutoRegLib] (AutoRegLib-1.3-15.jar) 
	U	betterbuilderswands{0.11.1} [Better Builder's Wands] (BetterBuildersWands-1.12-0.11.1.245+69d0d70.jar) 
	U	biomesoplenty{7.0.0.2291} [Biomes O' Plenty] (BiomesOPlenty-1.12-7.0.0.2291-universal.jar) 
	U	bookshelf{2.1.441} [Bookshelf] (Bookshelf-1.12.1-2.1.441.jar) 
	U	brandonscore{2.3.7} [Brandon's Core] (BrandonsCore-1.12-2.3.7.140-universal.jar) 
	U	chameleon{1.12-4.1.3} [Chameleon] (Chameleon-1.12-4.1.3.jar) 
	U	chickenchunks{2.4.0.70} [ChickenChunks] (ChickenChunks-1.12-2.4.0.70-universal.jar) 
	U	chisel{MC1.12-0.1.1.26} [Chisel] (Chisel-MC1.12-0.1.1.26.jar) 
	U	chiselsandbits{14.11} [Chisels & Bits] (chiselsandbits-14.11.jar) 
	U	codechickenlib{3.1.3.313} [CodeChicken Lib] (CodeChickenLib-1.12-3.1.3.313-universal.jar) 
	U	cofhcore{4.3.6} [CoFH Core] (CoFHCore-1.12-4.3.6.14-universal.jar) 
	U	cofhworld{1.0.1} [CoFH World] (CoFHWorld-1.12-1.0.1.8-universal.jar) 
	U	ctm{MC1.12-0.2.3.12} [CTM] (CTM-MC1.12-0.2.3.12.jar) 
	U	cucumber{1.0.4} [Cucumber] (cucumber-1.12-1.0.4.jar) 
	U	darkutils{1.7.171} [Dark Utilities] (DarkUtils-1.12.1-1.7.171.jar) 
	U	draconicevolution{2.3.8} [Draconic Evolution] (Draconic-Evolution-1.12-2.3.8.279-universal.jar) 
	U	elevatorid{1.3.4} [Elevator Mod] (ElevatorMod-1.12-1.3.4.jar) 
	U	enderstorage{2.4.0.122} [EnderStorage] (EnderStorage-1.12-2.4.0.122-universal.jar) 
	U	environmentaltech{1.12.X-2.0.4a} [Environmental Tech] (environmentaltech-1.12.X-2.0.4a.jar) 
	U	extrautils2{1.0} [Extra Utilities 2] (extrautils2-1.12-1.7.2.jar) 
	U	bigreactors{1.12-0.4.5.44} [Extreme Reactors] (ExtremeReactors-1.12-0.4.5.44.jar) 
	U	fastleafdecay{v13} [Fast Leaf Decay] (FastLeafDecay-v13.jar) 
	U	gravestone{1.8.4} [Gravestone Mod] (gravestone-1.8.4.jar) 
	U	waila{1.8.23} [Waila] (Hwyla-1.8.23-B38_1.12.jar) 
	U	industrialforegoing{null} [Industrial Foregoing] (industrialforegoing-1.12.2-1.5.10-98.jar) 
	U	ingameinfoxml{2.8.1.92} [InGame Info XML] (InGameInfoXML-1.12-2.8.1.92-universal.jar) 
	U	inventorytweaks{1.63+beta.107.015dbec} [Inventory Tweaks] (InventoryTweaks-1.63+beta.107.jar) 
	U	ironchest{1.12-7.0.31.818} [Iron Chest] (ironchest-1.12-7.0.31.818.jar) 
	U	jei{4.7.11.102} [Just Enough Items] (jei_1.12.2-4.7.11.102.jar) 
	U	journeymap{1.12-5.5.2} [JourneyMap] (journeymap-1.12-5.5.2.jar) 
	U	lunatriuscore{1.2.0.40} [LunatriusCore] (LunatriusCore-1.12-1.2.0.40-universal.jar) 
	U	mantle{1.12-1.3.1.21} [Mantle] (Mantle-1.12-1.3.1.21.jar) 
	U	mekanism{9.4.1} [Mekanism] (Mekanism-1.12.1-9.4.1.326.jar) 
	U	mob_grinding_utils{0.3.2} [mob_grinding_utils] (MobGrindingUtils-0.3.2.jar) 
	U	modnametooltip{1.9.0} [Mod Name Tooltip] (modnametooltip_1.12.1-1.9.0.jar) 
	U	mousetweaks{2.8} [Mouse Tweaks] (MouseTweaks-2.8-mc1.12.jar) 
	U	mysticalagradditions{1.2.7} [Mystical Agradditions] (mysticalagradditions-1.12-1.2.7.jar) 
	U	mysticalagriculture{1.6.7} [Mystical Agriculture] (mysticalagriculture-1.12-1.6.7.jar) 
	U	oreexcavation{1.4.104} [OreExcavation] (OreExcavation-1.4.104.jar) 
	U	harvestcraft{1.12.2a} [Pam's HarvestCraft] (Pam's HarvestCraft 1.12.2a.jar) 
	U	quantumstorage{4.4.5} [QuantumStorage] (QuantumStorage-1.12-4.4.5.jar) 
	U	randomthings{4.0.8} [Random Things] (RandomThings-MC1.12.2-4.0.8.jar) 
	U	rangedpumps{0.5} [Ranged Pumps] (rangedpumps-0.5.jar) 
	U	reborncore{3.6.5.197} [Reborn Core] (RebornCore-1.12.2-3.6.5.197-universal.jar) 
	U	redstoneflux{2.0.1} [Redstone Flux] (RedstoneFlux-1.12-2.0.1.2-universal.jar) 
	U	refinedstorage{1.5.28} [Refined Storage] (refinedstorage-1.5.28.jar) 
	U	refinedstorageaddons{0.2} [Refined Storage Addons] (refinedstorageaddons-0.2.jar) 
	U	rftools{6.13} [RFTools] (rftools-1.12-6.13.jar) 
	U	rftoolsdim{5.05} [RFTools Dimensions] (rftoolsdim-1.12-5.05.jar) 
	U	storagedrawers{1.12-5.2.5} [Storage Drawers] (StorageDrawers-1.12.2-5.3.4.jar) 
	U	tconstruct{1.12-2.8.1.49} [Tinkers' Construct] (TConstruct-1.12-2.8.1.49.jar) 
	U	thermaldynamics{2.3.6} [Thermal Dynamics] (ThermalDynamics-1.12-2.3.6.13-universal.jar) 
	U	thermalexpansion{5.3.6} [Thermal Expansion] (ThermalExpansion-1.12-5.3.6.20-universal.jar) 
	U	thermalfoundation{2.3.6} [Thermal Foundation] (ThermalFoundation-1.12-2.3.6.16-universal.jar) 
	U	tinkertoolleveling{1.12-1.0.3.DEV.56fac4f} [Tinkers Tool Leveling] (TinkerToolLeveling-1.12-1.0.3.jar) 
	U	valkyrielib{1.12-2.0.4b} [Valkyrie Lib] (valkyrielib-1.12.X-2.0.4b.jar) 
	U	wailaharvestability{1.1.12} [Waila Harvestability] (WailaHarvestability-mc1.12-1.1.12.jar) 
	U	wawla{2.5.243} [What Are We Looking At] (Wawla-1.12.1-2.5.243.jar) 
	U	wearablebackpacks{3.0.4} [Wearable Backpacks] (WearableBackpacks-1.12-3.0.4.jar) 
	U	zerocore{1.12-0.1.1.0} [Zero CORE] (zerocore-1.12-0.1.1.0.jar) 
	Loaded coremods (and transformers): 
CTMCorePlugin (CTM-MC1.12-0.2.3.12.jar)
  team.chisel.ctm.client.asm.CTMTransformer
LoadingPlugin (RandomThings-MC1.12.2-4.0.8.jar)
  lumien.randomthings.asm.ClassTransformer
Inventory Tweaks Coremod (InventoryTweaks-1.63+beta.107.jar)
  invtweaks.forge.asm.ContainerTransformer
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.5.13399 Compatibility Profile Context 15.201.1151.1008' Renderer: 'AMD Radeon HD 5700 Series'
	Launched Version: forge-14.21.1.2443
	LWJGL: 2.9.4
	OpenGL: AMD Radeon HD 5700 Series GL version 4.5.13399 Compatibility Profile Context 15.201.1151.1008, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i5-3340 CPU @ 3.10GHz

**Comment by raoulvdberge** [comment]
Not an RS issue
